# Generated by Django 6.1.1 on 2026-09-03 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Farinha, Leite, Ovo', max_length=120, unique=True, verbose_name='Nome do Ingrediente')),
                ('unidade', models.CharField(default='Kg', help_text='Ex: Kg, L, Unidade, g, dz', max_length=30, verbose_name='Unidade de Medida')),
                ('meta', models.DecimalField(decimal_places=2, help_text='Quantidade que o Seu Raimundo gosta de manter no início do mês', max_digits=10, verbose_name='Meta Mensal')),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, help_text='Sobra encontrada no final do mês', max_digits=10, verbose_name='Estoque Atual')),
                ('vencido', models.BooleanField(default=False, help_text='Se verdadeiro, todo o estoque atual é descartado e recompra-se a meta cheia', verbose_name='Venceu / Estragou?')),
                ('faltou_no_meio_do_mes', models.BooleanField(default=False, help_text='Se verdadeiro, a meta foi insuficiente: calcula sobre consumo real + 20% de margem', verbose_name='Acabou no meio do mês?')),
                ('consumo_real', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Se não informado e faltou no mês, assume o valor da meta consumida', max_digits=10, null=True, verbose_name='Consumo Real Registrado')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_itens', models.PositiveIntegerField(default=0)),
                ('conteudo_texto', models.TextField(verbose_name='Lista em Texto')),
            ],
            options={
                'verbose_name': 'Registro de Compra',
                'verbose_name_plural': 'Registros de Compras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
